[build]
command = "zola build"
publish = "public"

[build.environment]
ZOLA_VERSION = "0.21.0"

# Override the base url with whatever url Netlify assigns to our
# preview site. Do this by using the Netlify environment variable
# `$DEPLOY_PRIME_URL`.

[context.deploy-preview]
command = "zola build --base-url $DEPLOY_PRIME_URL"

#[[redirects]] changed
#  from = "/.well-known/host-meta*"
#  to = "https://fed.brid.gy/.well-known/host-meta:splat"
#  status = 302
#[[redirects]]
#  from = "/.well-known/webfinger*"
#  to = "https://fed.brid.gy/.well-known/webfinger"
#  status = 302